# auto-generated by idl_extractor.rb
class Performance
  class Navigation
    TYPE_RESERVED = 255
    TYPE_NAVIGATE = 0
    TYPE_RELOAD = 1
    TYPE_BACK_FORWARD = 2
    attr_reader :type, :redirect_count
    def initialize args
      args.each do |k,v|
        instance_variable_set("@#{k}", v) if respond_to?(k.to_sym) unless v.nil?
      end
    end
  end
  class Timing
    attr_reader :navigation_start, :unload_event_start, :unload_event_end, :redirect_start, :redirect_end, :fetch_start, :domain_lookup_start, :domain_lookup_end, :connect_start, :connect_end, :secure_connection_start, :request_start, :response_start, :response_end, :dom_loading, :dom_interactive, :dom_content_loaded_event_start, :dom_content_loaded_event_end, :dom_complete, :load_event_start, :load_event_end
    def initialize args
      args.each do |k,v|
        instance_variable_set("@#{k}", v) if respond_to?(k.to_sym) unless v.nil?
      end
    end
  end
end
